### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by LuKeLnx** [tipoc123/pumpbot#1]
`c:\pumpbot-master>php pump_capitan_volume.php
getMarketSummaries BEFORE

Notice: Trying to get property of non-object in C:\pumpbot-master\Client.php on line 51

Notice: Trying to get property of non-object in C:\pumpbot-master\Client.php on line 52

Fatal error: Uncaught Exception in C:\pumpbot-master\Client.php:52
Stack trace:
#0 C:\pumpbot-master\Client.php(92): Client->call('public/getmarke...')
#1 C:\pumpbot-master\pump_capitan_volume.php(17): Client->getMarketSummaries()
#2 {main}
  thrown in C:\pumpbot-master\Client.php on line 52`

**Comment by tipoc123** [comment]
```
~/Desktop/1/pumpbot$ git clone https://github.com/tipoc123/pumpbot.git
~/Desktop/1/pumpbot$ cd pumpbot
~/Desktop/1/pumpbot$ php pump_capitan_volume.php
getMarketSummaries BEFORE
getMarketSummaries OK
...
```
Works fine (Ubuntu 16.04)
